export const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
  DELETED: "DELETED",
} as const;

export const UNIT_STATUS = {
  VACANT: "VACANT",
  OCCUPIED: "OCCUPIED",
  OWNER_STAY: "OWNER_STAY",
  MAINTENANCE: "MAINTENANCE",
  HOUSEKEEPING: "HOUSEKEEPING",
  RESERVED: "RESERVED",
} as const;

export const WORKORDER_STATUS = {
  OPEN: "OPEN",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const VISITOR_STATUS = {
  WAITING: "WAITING",
  CHECKED_IN: "CHECKED_IN",
  CHECKED_OUT: "CHECKED_OUT",
  CANCELLED: "CANCELLED",
} as const;